services:
    ezcom.cheveretotab.listener:
        class: ezcom\cheveretotab\event\listener
        arguments:
            - '@auth'
            - '@config'
            - '@template'
            - '@user'
            - '@request'
        tags:
            - {name: event.listener}
